dict_value {
  fields {
    key: "collect_data_spec"
    value {
      named_tuple_value {
        name: "Trajectory"
        values {
          key: "step_type"
          value {
            tensor_spec_value {
              name: "step_type"
              shape {
              }
              dtype: DT_INT32
            }
          }
        }
        values {
          key: "observation"
          value {
            dict_value {
              fields {
                key: "current_node"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/current_node"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_INT32
                    minimum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 0
                    }
                    maximum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 4999
                    }
                  }
                }
              }
              fields {
                key: "edge_counts"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/edge_counts"
                    shape {
                      dim {
                        size: 5000
                      }
                    }
                    dtype: DT_INT32
                    minimum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 0
                    }
                    maximum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 28399
                    }
                  }
                }
              }
              fields {
                key: "grid_cols"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/grid_cols"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "grid_rows"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/grid_rows"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "horizontal_routes_per_micron"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/horizontal_routes_per_micron"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 100.0
                    }
                  }
                }
              }
              fields {
                key: "is_node_placed"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/is_node_placed"
                    shape {
                      dim {
                        size: 5000
                      }
                    }
                    dtype: DT_INT32
                    minimum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 0
                    }
                    maximum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 1
                    }
                  }
                }
              }
              fields {
                key: "locations_x"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/locations_x"
                    shape {
                      dim {
                        size: 5000
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "locations_y"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/locations_y"
                    shape {
                      dim {
                        size: 5000
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "macro_horizontal_routing_allocation"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/macro_horizontal_routing_allocation"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 100.0
                    }
                  }
                }
              }
              fields {
                key: "macro_vertical_routing_allocation"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/macro_vertical_routing_allocation"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 100.0
                    }
                  }
                }
              }
              fields {
                key: "macros_h"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/macros_h"
                    shape {
                      dim {
                        size: 5000
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "macros_w"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/macros_w"
                    shape {
                      dim {
                        size: 5000
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "mask"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/mask"
                    shape {
                      dim {
                        size: 16384
                      }
                    }
                    dtype: DT_INT32
                    minimum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 0
                    }
                    maximum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 1
                    }
                  }
                }
              }
              fields {
                key: "node_types"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/node_types"
                    shape {
                      dim {
                        size: 5000
                      }
                    }
                    dtype: DT_INT32
                    minimum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 0
                    }
                    maximum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 3
                    }
                  }
                }
              }
              fields {
                key: "normalized_num_edges"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/normalized_num_edges"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "normalized_num_hard_macros"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/normalized_num_hard_macros"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "normalized_num_port_clusters"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/normalized_num_port_clusters"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "normalized_num_soft_macros"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/normalized_num_soft_macros"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 1.0
                    }
                  }
                }
              }
              fields {
                key: "sparse_adj_i"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/sparse_adj_i"
                    shape {
                      dim {
                        size: 28400
                      }
                    }
                    dtype: DT_INT32
                    minimum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 0
                    }
                    maximum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 4999
                    }
                  }
                }
              }
              fields {
                key: "sparse_adj_j"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/sparse_adj_j"
                    shape {
                      dim {
                        size: 28400
                      }
                    }
                    dtype: DT_INT32
                    minimum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 0
                    }
                    maximum {
                      dtype: DT_INT32
                      tensor_shape {
                      }
                      int_val: 4999
                    }
                  }
                }
              }
              fields {
                key: "sparse_adj_weight"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/sparse_adj_weight"
                    shape {
                      dim {
                        size: 28400
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 100.0
                    }
                  }
                }
              }
              fields {
                key: "vertical_routes_per_micron"
                value {
                  bounded_tensor_spec_value {
                    name: "observation/vertical_routes_per_micron"
                    shape {
                      dim {
                        size: 1
                      }
                    }
                    dtype: DT_FLOAT
                    minimum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 0.0
                    }
                    maximum {
                      dtype: DT_FLOAT
                      tensor_shape {
                      }
                      float_val: 100.0
                    }
                  }
                }
              }
            }
          }
        }
        values {
          key: "action"
          value {
            bounded_tensor_spec_value {
              name: "action"
              shape {
              }
              dtype: DT_INT64
              minimum {
                dtype: DT_INT64
                tensor_shape {
                }
                int64_val: 0
              }
              maximum {
                dtype: DT_INT64
                tensor_shape {
                }
                int64_val: 16383
              }
            }
          }
        }
        values {
          key: "policy_info"
          value {
            dict_value {
              fields {
                key: "dist_params"
                value {
                  dict_value {
                    fields {
                      key: "logits"
                      value {
                        tensor_spec_value {
                          name: "GrlPolicyModel_logits"
                          shape {
                            dim {
                              size: 16384
                            }
                          }
                          dtype: DT_FLOAT
                        }
                      }
                    }
                  }
                }
              }
              fields {
                key: "value_prediction"
                value {
                  tensor_spec_value {
                    shape {
                    }
                    dtype: DT_FLOAT
                  }
                }
              }
            }
          }
        }
        values {
          key: "next_step_type"
          value {
            tensor_spec_value {
              name: "step_type"
              shape {
              }
              dtype: DT_INT32
            }
          }
        }
        values {
          key: "reward"
          value {
            tensor_spec_value {
              name: "reward"
              shape {
              }
              dtype: DT_FLOAT
            }
          }
        }
        values {
          key: "discount"
          value {
            bounded_tensor_spec_value {
              name: "discount"
              shape {
              }
              dtype: DT_FLOAT
              minimum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 0.0
              }
              maximum {
                dtype: DT_FLOAT
                tensor_shape {
                }
                float_val: 1.0
              }
            }
          }
        }
      }
    }
  }
  fields {
    key: "policy_state_spec"
    value {
      tuple_value {
      }
    }
  }
}
